apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:platform, applications, get, */*, allow
    p, role:platform, applications, update, */*, allow
    p, role:platform, applications, delete, */*, allow
    g, platform-team, role:platform
